source 'http://rubygems.org'
gem 'watir-webdriver', '~> 0.7.0'
gem 'headless', '~> 1.0.2'
gem 'rspec', '~> 3.2.0'
gem 'cucumber', '~> 1.3.18'
gem 'watir', '~> 5.0.0'
gem 'rspec-expectations', '~> 3.2.0'
gem 'watir-webdriver-performance', '~> 0.2.4'
gem 'naturalsort', '~> 1.2.0'
gem 'cucumber-rails'
gem 'page-object'
gem 'watir-page-helper'
gem 'minitest'
gem 'watirgrid'
gem 'em-dir-watcher'
gem 'eventmachine'
gem 'au3'

